# Generated by Django 4.0.4 on 2022-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
