# Generated by Django 4.0.4 on 2022-06-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_starting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='starting_price',
        ),
    ]
