# Generated by Django 4.0.4 on 2022-07-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='following',
        ),
    ]
