# Generated by Django 4.0.4 on 2022-07-21 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_post_like_post_liked_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mood',
        ),
        migrations.AddField(
            model_name='follower',
            name='mood',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
